import * as THREE from './vendor/three.module.js';
import {createDog,animateDog} from './dog3d.js';

const C={road:'#a8b8c1',rail:'#5e7e8d',cyan:'#52e5ef',ink:'#122f3b'};
function mat(color,roughness=.8,metalness=0){return new THREE.MeshStandardMaterial({color,roughness,metalness});}
function label(text,bg='#0c7186',fg='#ffffff',w=256,h=128){
  const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,w,h);x.strokeStyle='#d1fdff';x.lineWidth=8;x.strokeRect(7,7,w-14,h-14);x.fillStyle=fg;x.textAlign='center';x.textBaseline='middle';x.font=`900 ${text.length>8?39:65}px system-ui`;x.fillText(text,w/2,h/2);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;
}
function roadTexture(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.fillStyle='#acbac0';x.fillRect(0,0,512,512);let seed=12971;const rand=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);for(let i=0;i<9500;i++){const v=120+rand()*80;x.fillStyle=`rgba(${v},${v+6},${v+8},${.025+rand()*.07})`;x.fillRect(rand()*512,rand()*512,1+rand()*5,1+rand()*5);}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(2,18);t.colorSpace=THREE.SRGBColorSpace;return t;}
function mergeDogGeometry(kind,id){
  const src=createDog(kind,id,1,'low');src.updateMatrixWorld(true);
  const p=[],norm=[],colors=[],indices=[];let offset=0;
  src.traverse(o=>{if(!o.isMesh||o.material.transparent)return;const a=o.geometry.attributes.position,n=o.geometry.attributes.normal,ix=o.geometry.index;const color=o.material.color||new THREE.Color('#b29471');const nm=new THREE.Matrix3().getNormalMatrix(o.matrixWorld);const v=new THREE.Vector3(),q=new THREE.Vector3();for(let i=0;i<a.count;i++){v.fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld);q.fromBufferAttribute(n,i).applyMatrix3(nm).normalize();p.push(v.x,v.y,v.z);norm.push(q.x,q.y,q.z);colors.push(color.r,color.g,color.b);}if(ix){for(let i=0;i<ix.count;i++)indices.push(offset+ix.getX(i));}else{for(let i=0;i<a.count;i++)indices.push(offset+i);}offset+=a.count;});
  const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(norm,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.setIndex(indices);g.computeBoundingSphere();return g;
}

export function createWorld(canvas){
  const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.65));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.16;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
  const scene=new THREE.Scene();scene.background=new THREE.Color('#86bbd0');scene.fog=new THREE.FogExp2('#9cc8d6',.0105);
  const camera=new THREE.PerspectiveCamera(52,1,.1,180);camera.position.set(0,7.7,-14.1);camera.lookAt(0,1.2,13);
  const hemi=new THREE.HemisphereLight('#f6fcff','#55748b',2.2);scene.add(hemi);
  const sun=new THREE.DirectionalLight('#fff5dc',2.5);sun.position.set(-14,28,22);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-24;sun.shadow.camera.right=24;sun.shadow.camera.top=32;sun.shadow.camera.bottom=-24;sun.shadow.camera.near=.1;sun.shadow.camera.far=90;sun.shadow.bias=-.00015;scene.add(sun);
  const frontFill=new THREE.DirectionalLight('#d1edff',1.15);frontFill.position.set(6,10,-14);scene.add(frontFill);
  const skyGeo=new THREE.PlaneGeometry(220,90);const sky=new THREE.Mesh(skyGeo,new THREE.ShaderMaterial({depthWrite:false,side:THREE.DoubleSide,vertexShader:'varying vec2 vUv; void main(){vUv=uv; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv; void main(){vec3 low=vec3(.67,.84,.88); vec3 mid=vec3(.38,.68,.85); vec3 high=vec3(.18,.43,.67); vec3 c=mix(low,mid,smoothstep(.0,.55,vUv.y)); c=mix(c,high,smoothstep(.45,1.,vUv.y)); float haze=.13*sin(vUv.x*13.+vUv.y*8.); c+=haze*vec3(.15,.18,.18);gl_FragColor=vec4(c,1.);}'}));sky.position.set(0,24,100);scene.add(sky);
  const water=new THREE.Mesh(new THREE.PlaneGeometry(240,260),new THREE.ShaderMaterial({uniforms:{uTime:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform float uTime;varying vec2 vUv;void main(){vec2 p=vUv*vec2(42.,65.);float a=sin(p.x*1.3+p.y*.75+uTime*.8);float b=sin(p.x*.57-p.y*1.75-uTime*1.1);float foam=pow(max(0.,a*b),8.);vec3 blue=mix(vec3(.025,.30,.49),vec3(.04,.52,.69),.5+.22*a+.18*b);blue+=foam*vec3(.35,.36,.29);gl_FragColor=vec4(blue,1.);}'}));water.rotation.x=-Math.PI/2;water.position.set(0,-1.5,32);scene.add(water);
  const bridge=new THREE.Group();scene.add(bridge);
  const deck=new THREE.Mesh(new THREE.BoxGeometry(11,.68,150),new THREE.MeshStandardMaterial({map:roadTexture(),roughness:.97,color:'#e3e4df'}));deck.position.set(0,-.34,29);deck.receiveShadow=true;bridge.add(deck);
  const edgeM=mat('#d2dee0',.75,.12),darkM=mat('#3c5b65',.54,.55),lineM=new THREE.MeshBasicMaterial({color:'#eaf9f8'});
  for(const side of [-1,1]){
    const curb=new THREE.Mesh(new THREE.BoxGeometry(.38,.42,150),edgeM);curb.position.set(side*5.4,.17,29);curb.receiveShadow=true;bridge.add(curb);
    for(let z=-20;z<78;z+=4){const post=new THREE.Mesh(new THREE.BoxGeometry(.22,1.5,.22),darkM);post.position.set(side*5.52,.99,z);post.castShadow=false;bridge.add(post);}
    for(const y of [.9,1.43]){const rail=new THREE.Mesh(new THREE.BoxGeometry(.14,.14,150),darkM);rail.position.set(side*5.52,y,29);bridge.add(rail);}
    for(let z=-18;z<78;z+=12){const support=new THREE.Mesh(new THREE.BoxGeometry(.35,7,.35),darkM);support.position.set(side*5.2,-4.2,z);bridge.add(support);}
  }
  const roadMarks=[];for(let i=0;i<42;i++){const m=new THREE.Mesh(new THREE.PlaneGeometry(.10,1.25),lineM);m.rotation.x=-Math.PI/2;m.position.set(0,.018,-18+i*2.4);bridge.add(m);roadMarks.push(m);}
  for(const z of [75,120]){const span=new THREE.Mesh(new THREE.BoxGeometry(31,.45,.45),darkM);span.position.set(0,13,z);scene.add(span);for(const side of [-1,1]){const p=new THREE.Mesh(new THREE.BoxGeometry(.5,14,.5),darkM);p.position.set(side*11,6,z);scene.add(p);}}
  let heroId='gerrard',leader=null,near=[],army=null,armyCount=1,armyX=0,entities=[],bullets=[],effects=[],rings=[],time=0;
  const enemyShapes=new Map(),enemyMaterial=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.88,metalness:0,side:THREE.DoubleSide});
  const dummy=new THREE.Object3D(),bulletGeo=new THREE.BufferGeometry(),maxBullet=360,bulletPos=new Float32Array(maxBullet*18);bulletGeo.setAttribute('position',new THREE.BufferAttribute(bulletPos,3).setUsage(THREE.DynamicDrawUsage));bulletGeo.setDrawRange(0,0);const bulletMesh=new THREE.Mesh(bulletGeo,new THREE.MeshBasicMaterial({color:'#d6fcff',transparent:true,opacity:.93,side:THREE.DoubleSide,depthWrite:false}));bulletMesh.frustumCulled=false;scene.add(bulletMesh);
  const burstGeo=new THREE.BufferGeometry(),burstPos=new Float32Array(300*3),burstColor=new Float32Array(300*3);burstGeo.setAttribute('position',new THREE.BufferAttribute(burstPos,3).setUsage(THREE.DynamicDrawUsage));burstGeo.setAttribute('color',new THREE.BufferAttribute(burstColor,3).setUsage(THREE.DynamicDrawUsage));const burstPoints=new THREE.Points(burstGeo,new THREE.PointsMaterial({vertexColors:true,size:.16,transparent:true,opacity:.85,depthWrite:false}));burstPoints.frustumCulled=false;scene.add(burstPoints);
  function clear(){for(const e of entities)scene.remove(e.mesh);entities=[];effects=[];bullets=[];for(const r of rings){scene.remove(r.mesh);r.mesh.geometry.dispose();r.mesh.material.dispose();}rings=[];if(leader)scene.remove(leader);for(const d of near)scene.remove(d);near=[];if(army)scene.remove(army);army=null;}
  function reset(id){clear();heroId=id;leader=createDog('hero',id,1.05,'high');leader.castShadow=true;scene.add(leader);for(let i=0;i<7;i++){const d=createDog('hero',id,.84,'medium');d.traverse(o=>{if(o.isMesh)o.castShadow=false});near.push(d);scene.add(d);}army=new THREE.InstancedMesh(mergeDogGeometry('hero',id),new THREE.MeshStandardMaterial({vertexColors:true,roughness:.9,metalness:0,side:THREE.DoubleSide}),100);army.instanceMatrix.setUsage(THREE.DynamicDrawUsage);army.count=0;army.castShadow=false;army.frustumCulled=false;scene.add(army);armyCount=1;armyX=0;}
  function formation(i,count){if(i===0)return {x:0,z:1.1};const cols=Math.min(7,Math.max(3,Math.ceil(Math.sqrt(count*.8)))),n=i-1,row=Math.floor(n/cols),col=n%cols;return {x:(col-(cols-1)/2)*1.05,z:.15-row*1.04};}
  function squad(count,x,t){armyCount=Math.min(100,count);armyX=x;leader.position.set(x,0,1.1);leader.rotation.y=(x-leader.userData.lastX||0)*-.018;leader.userData.lastX=x;animateDog(leader,t,1);
    const nearN=Math.min(near.length,Math.max(0,armyCount-1));for(let i=0;i<near.length;i++){const d=near[i];d.visible=i<nearN;if(!d.visible)continue;const f=formation(i+1,armyCount);d.position.set(Math.max(-4.55,Math.min(4.55,x+f.x)),0,f.z);animateDog(d,t,.95+i*.015);}
    let n=0;for(let i=nearN+1;i<armyCount;i++){const f=formation(i,armyCount);dummy.position.set(Math.max(-4.55,Math.min(4.55,x+f.x)),.022+Math.abs(Math.sin(t*10+i*2.15))*.028,f.z);dummy.rotation.set(0,0,0);dummy.scale.setScalar(.72);dummy.updateMatrix();army.setMatrixAt(n++,dummy.matrix);}army.count=n;army.instanceMatrix.needsUpdate=true;
  }
  function addEnemy(kind,x,z,boss=false){let d;if(boss){d=createDog(kind,heroId,kind==='xlbully'?3.7:3.2,'high');d.traverse(o=>{if(o.isMesh)o.castShadow=true});}else{if(!enemyShapes.has(kind))enemyShapes.set(kind,mergeDogGeometry(kind,heroId));d=new THREE.Mesh(enemyShapes.get(kind),enemyMaterial);d.scale.setScalar(.9);d.receiveShadow=true;}d.position.set(x,0,z);d.rotation.y=Math.PI;scene.add(d);const e={mesh:d,kind,boss,z,x,phase:Math.random()*6.28};entities.push(e);return e;}
  function gateTexture(text){return new THREE.MeshBasicMaterial({map:label(text),transparent:true,side:THREE.DoubleSide,depthWrite:false});}
  function addGate(text,x,z){const group=new THREE.Group(),frameM=mat('#12a6bb',.48,.35),panel=new THREE.Mesh(new THREE.PlaneGeometry(2.1,1.45),gateTexture(text));panel.position.set(0,1.26,0);panel.rotation.y=Math.PI;group.add(panel);for(const side of [-1,1]){const p=new THREE.Mesh(new THREE.BoxGeometry(.12,2.2,.18),frameM);p.position.set(side*1.08,1.12,0);group.add(p);}const beam=new THREE.Mesh(new THREE.BoxGeometry(2.28,.13,.2),frameM);beam.position.set(0,2.18,0);group.add(beam);group.position.set(x,0,z);scene.add(group);const e={mesh:group,kind:'gate',z,x,text};entities.push(e);return e;}
  function blockerTexture(hp){return new THREE.MeshBasicMaterial({map:label(String(Math.ceil(hp)),'#27363c','#ffffff',256,128),transparent:true,side:THREE.DoubleSide});}
  function addBlocker(x,z,hp){const group=new THREE.Group(),wood=mat('#a77747',.93),dark=mat('#554735',.85),metal=mat('#697780',.4,.55);const body=new THREE.Mesh(new THREE.BoxGeometry(2.55,2.0,1.5),wood);body.position.y=1.03;body.castShadow=true;body.receiveShadow=true;group.add(body);for(const y of [.34,.76,1.17,1.58]){const board=new THREE.Mesh(new THREE.BoxGeometry(2.65,.08,1.62),dark);board.position.y=y;group.add(board);}for(const side of [-1,1]){const band=new THREE.Mesh(new THREE.BoxGeometry(.12,2.16,1.68),metal);band.position.set(side*.93,1.05,0);group.add(band);}const hpLabel=new THREE.Mesh(new THREE.PlaneGeometry(1.9,.95),blockerTexture(hp));hpLabel.position.set(0,2.48,-.81);hpLabel.rotation.y=Math.PI;group.add(hpLabel);group.position.set(x,0,z);scene.add(group);const e={mesh:group,kind:'blocker',z,x,hp,hpLabel};entities.push(e);return e;}
  function setBlockerHp(e,hp){if(!e?.hpLabel)return;e.hpLabel.material.map.dispose();e.hpLabel.material.dispose();e.hpLabel.material=blockerTexture(hp);e.mesh.rotation.z=(Math.random()-.5)*.025;}
  function remove(e){const i=entities.indexOf(e);if(i>=0)entities.splice(i,1);scene.remove(e.mesh);}
  function impact(x,z,color='#b7faff',count=9){const c=new THREE.Color(color);for(let i=0;i<count;i++)effects.push({x,y:.5+Math.random()*.7,z,vx:(Math.random()-.5)*5,vy:Math.random()*5,vz:(Math.random()-.5)*5,life:.35+Math.random()*.3,color:c});if(effects.length>240)effects.splice(0,effects.length-240);if(count>=30){const m=new THREE.Mesh(new THREE.RingGeometry(1,1.1,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(x,.06,z);m.scale.setScalar(.15);scene.add(m);rings.push({mesh:m,age:0});}}
  function update(dt,t,count,x,projectiles){time=t;water.material.uniforms.uTime.value=t;water.material.uniformsNeedUpdate=true;deck.material.map.offset.y=-t*.09;for(let i=0;i<roadMarks.length;i++)roadMarks[i].position.z=-18+((i*2.4-t*8)%100+100)%100;
    squad(count,x,t);
    for(const e of entities){if(e.kind==='gate'||e.kind==='blocker'){e.mesh.position.z=e.z;continue;}e.mesh.position.set(e.x,e.boss?0:Math.abs(Math.sin(t*11+e.phase))*.035,e.z);if(e.boss)animateDog(e.mesh,t+e.phase,.74,'run');else e.mesh.rotation.z=Math.sin(t*6+e.phase)*.015;}
    const cap=Math.min(maxBullet,projectiles.length);for(let i=0;i<cap;i++){const b=projectiles[i],o=i*18,x=b.x,z=b.z,y=b.y||.68,len=b.len||.65,w=b.w||.027;bulletPos.set([x-w,y,z,x+w,y,z,x-w,y,z-len,x+w,y,z,x+w,y,z-len,x-w,y,z-len],o);}bulletGeo.setDrawRange(0,cap*6);bulletGeo.attributes.position.needsUpdate=true;
    for(const p of effects){p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vy-=11*dt;p.life-=dt;}effects=effects.filter(p=>p.life>0);for(let i=0;i<effects.length;i++){const p=effects[i];burstPos.set([p.x,p.y,p.z],i*3);burstColor.set([p.color.r,p.color.g,p.color.b],i*3);}burstGeo.setDrawRange(0,effects.length);burstGeo.attributes.position.needsUpdate=true;burstGeo.attributes.color.needsUpdate=true;
    for(let i=rings.length-1;i>=0;i--){const r=rings[i];r.age+=dt;r.mesh.scale.setScalar(.15+r.age*7);r.mesh.material.opacity=Math.max(0,.8-r.age);if(r.age>.8){scene.remove(r.mesh);r.mesh.geometry.dispose();r.mesh.material.dispose();rings.splice(i,1);}}
    const targetX=x*.13;camera.position.x+=(targetX-camera.position.x)*Math.min(1,dt*2.2);camera.position.z+=((-14.1-Math.min(7,count*.07))-camera.position.z)*Math.min(1,dt*1.4);camera.position.y+=((7.7+Math.min(2.2,count*.023))-camera.position.y)*Math.min(1,dt*1.4);camera.lookAt(camera.position.x*.38,1.25,14);
  }
  function resize(w,h){renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=h/w>2.2?53:50;camera.updateProjectionMatrix();}
  function render(){renderer.render(scene,camera);}
  function project(x,y,z){const v=new THREE.Vector3(x,y,z).project(camera);return {x:(v.x*.5+.5)*renderer.domElement.clientWidth,y:(-.5*v.y+.5)*renderer.domElement.clientHeight,visible:v.z<1&&v.z>-1};}
  reset(heroId);return {renderer,scene,camera,reset,resize,render,update,addEnemy,addGate,addBlocker,setBlockerHp,remove,impact,project,get entities(){return entities;}};
}
